version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000